- name: Ensure TCP wrapper file allows Nagios server
  lineinfile:
    dest: /etc/hosts.allow
    line: 'nrpe: 10.3.223.100'

- name: setting nrpe.conf
  template:
    src="nrpe_conf.j2"
    dest="/etc/nagios/nrpe.cfg"
    owner=root
    group=root
    mode=0644
  notify:
    - restart nagios 

- name: Ensure firewall port is open
  firewalld:
    zone: public
    port: 5666/tcp
    permanent: true
    state: enabled
#    when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
  notify: 
    - restart nagios
