---
- hosts: all
  become: yes

  roles:
    - { role: common, tags: ['common'] }
    - { role: docker, tags: ['docker'] }
    - { role: zabbix, tags: ['zabbix'] }
    - { role: nagios, tags: ['nagios'] }
    - { role: splunk, tags: ['splunk'] }
